// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "Lesson-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // Lesson
  //

  struct access::object_traits_impl< ::Lesson, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::Lesson, id_mysql >::id_type
  access::object_traits_impl< ::Lesson, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::Lesson, id_mysql >::id_type
  access::object_traits_impl< ::Lesson, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::Lesson, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _id
    //
    t[0UL] = 0;

    // _title
    //
    if (t[1UL])
    {
      i._title_value.capacity (i._title_size);
      grew = true;
    }

    // _description
    //
    if (t[2UL])
    {
      i._description_value.capacity (i._description_size);
      grew = true;
    }

    // _teacher
    //
    if (t[3UL])
    {
      i._teacher_value.capacity (i._teacher_size);
      grew = true;
    }

    // _location
    //
    if (t[4UL])
    {
      i._location_value.capacity (i._location_size);
      grew = true;
    }

    // _startdate
    //
    if (t[5UL])
    {
      i._startdate_value.capacity (i._startdate_size);
      grew = true;
    }

    // _enddate
    //
    if (t[6UL])
    {
      i._enddate_value.capacity (i._enddate_size);
      grew = true;
    }

    // _year
    //
    if (t[7UL])
    {
      i._year_value.capacity (i._year_size);
      grew = true;
    }

    // _type
    //
    if (t[8UL])
    {
      i._type_value.capacity (i._type_size);
      grew = true;
    }

    // _weekNr
    //
    t[9UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::Lesson, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // _id
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _title
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._title_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._title_value.capacity ());
    b[n].length = &i._title_size;
    b[n].is_null = &i._title_null;
    n++;

    // _description
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._description_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._description_value.capacity ());
    b[n].length = &i._description_size;
    b[n].is_null = &i._description_null;
    n++;

    // _teacher
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._teacher_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._teacher_value.capacity ());
    b[n].length = &i._teacher_size;
    b[n].is_null = &i._teacher_null;
    n++;

    // _location
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._location_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._location_value.capacity ());
    b[n].length = &i._location_size;
    b[n].is_null = &i._location_null;
    n++;

    // _startdate
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._startdate_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._startdate_value.capacity ());
    b[n].length = &i._startdate_size;
    b[n].is_null = &i._startdate_null;
    n++;

    // _enddate
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._enddate_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._enddate_value.capacity ());
    b[n].length = &i._enddate_size;
    b[n].is_null = &i._enddate_null;
    n++;

    // _year
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._year_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._year_value.capacity ());
    b[n].length = &i._year_size;
    b[n].is_null = &i._year_null;
    n++;

    // _type
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._type_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._type_value.capacity ());
    b[n].length = &i._type_size;
    b[n].is_null = &i._type_null;
    n++;

    // _weekNr
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i._weekNr_value;
    b[n].is_null = &i._weekNr_null;
    n++;
  }

  void access::object_traits_impl< ::Lesson, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Lesson, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // _id
    //
    if (sk == statement_insert)
    {
      long unsigned int const& v =
        o._id;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i._id_value, is_null, v);
      i._id_null = is_null;
    }

    // _title
    //
    {
      ::std::string const& v =
        o._title;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._title_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._title_value,
        size,
        is_null,
        v);
      i._title_null = is_null;
      i._title_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._title_value.capacity ());
    }

    // _description
    //
    {
      ::std::string const& v =
        o._description;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._description_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._description_value,
        size,
        is_null,
        v);
      i._description_null = is_null;
      i._description_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._description_value.capacity ());
    }

    // _teacher
    //
    {
      ::std::string const& v =
        o._teacher;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._teacher_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._teacher_value,
        size,
        is_null,
        v);
      i._teacher_null = is_null;
      i._teacher_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._teacher_value.capacity ());
    }

    // _location
    //
    {
      ::std::string const& v =
        o._location;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._location_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._location_value,
        size,
        is_null,
        v);
      i._location_null = is_null;
      i._location_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._location_value.capacity ());
    }

    // _startdate
    //
    {
      ::std::string const& v =
        o._startdate;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._startdate_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._startdate_value,
        size,
        is_null,
        v);
      i._startdate_null = is_null;
      i._startdate_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._startdate_value.capacity ());
    }

    // _enddate
    //
    {
      ::std::string const& v =
        o._enddate;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._enddate_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._enddate_value,
        size,
        is_null,
        v);
      i._enddate_null = is_null;
      i._enddate_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._enddate_value.capacity ());
    }

    // _year
    //
    {
      ::std::string const& v =
        o._year;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._year_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._year_value,
        size,
        is_null,
        v);
      i._year_null = is_null;
      i._year_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._year_value.capacity ());
    }

    // _type
    //
    {
      ::std::string const& v =
        o._type;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._type_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._type_value,
        size,
        is_null,
        v);
      i._type_null = is_null;
      i._type_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._type_value.capacity ());
    }

    // _weekNr
    //
    {
      int const& v =
        o._weekNr;

      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i._weekNr_value, is_null, v);
      i._weekNr_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::Lesson, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _id
    //
    {
      long unsigned int& v =
        o._id;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _title
    //
    {
      ::std::string& v =
        o._title;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._title_value,
        i._title_size,
        i._title_null);
    }

    // _description
    //
    {
      ::std::string& v =
        o._description;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._description_value,
        i._description_size,
        i._description_null);
    }

    // _teacher
    //
    {
      ::std::string& v =
        o._teacher;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._teacher_value,
        i._teacher_size,
        i._teacher_null);
    }

    // _location
    //
    {
      ::std::string& v =
        o._location;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._location_value,
        i._location_size,
        i._location_null);
    }

    // _startdate
    //
    {
      ::std::string& v =
        o._startdate;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._startdate_value,
        i._startdate_size,
        i._startdate_null);
    }

    // _enddate
    //
    {
      ::std::string& v =
        o._enddate;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._enddate_value,
        i._enddate_size,
        i._enddate_null);
    }

    // _year
    //
    {
      ::std::string& v =
        o._year;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._year_value,
        i._year_size,
        i._year_null);
    }

    // _type
    //
    {
      ::std::string& v =
        o._type;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._type_value,
        i._type_size,
        i._type_null);
    }

    // _weekNr
    //
    {
      int& v =
        o._weekNr;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i._weekNr_value,
        i._weekNr_null);
    }
  }

  void access::object_traits_impl< ::Lesson, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::Lesson, id_mysql >::persist_statement[] =
  "INSERT INTO `Lesson` "
  "(`id`, "
  "`title`, "
  "`description`, "
  "`teacher`, "
  "`location`, "
  "`startdate`, "
  "`enddate`, "
  "`year`, "
  "`type`, "
  "`weekNr`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Lesson, id_mysql >::find_statement[] =
  "SELECT "
  "`Lesson`.`id`, "
  "`Lesson`.`title`, "
  "`Lesson`.`description`, "
  "`Lesson`.`teacher`, "
  "`Lesson`.`location`, "
  "`Lesson`.`startdate`, "
  "`Lesson`.`enddate`, "
  "`Lesson`.`year`, "
  "`Lesson`.`type`, "
  "`Lesson`.`weekNr` "
  "FROM `Lesson` "
  "WHERE `Lesson`.`id`=?";

  const char access::object_traits_impl< ::Lesson, id_mysql >::update_statement[] =
  "UPDATE `Lesson` "
  "SET "
  "`title`=?, "
  "`description`=?, "
  "`teacher`=?, "
  "`location`=?, "
  "`startdate`=?, "
  "`enddate`=?, "
  "`year`=?, "
  "`type`=?, "
  "`weekNr`=? "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::Lesson, id_mysql >::erase_statement[] =
  "DELETE FROM `Lesson` "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::Lesson, id_mysql >::query_statement[] =
  "SELECT "
  "`Lesson`.`id`, "
  "`Lesson`.`title`, "
  "`Lesson`.`description`, "
  "`Lesson`.`teacher`, "
  "`Lesson`.`location`, "
  "`Lesson`.`startdate`, "
  "`Lesson`.`enddate`, "
  "`Lesson`.`year`, "
  "`Lesson`.`type`, "
  "`Lesson`.`weekNr` "
  "FROM `Lesson`";

  const char access::object_traits_impl< ::Lesson, id_mysql >::erase_query_statement[] =
  "DELETE FROM `Lesson`";

  const char access::object_traits_impl< ::Lesson, id_mysql >::table_name[] =
  "`Lesson`";

  void access::object_traits_impl< ::Lesson, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im._id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj._id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Lesson, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Lesson, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::Lesson, id_mysql >::pointer_type
  access::object_traits_impl< ::Lesson, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Lesson, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Lesson, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Lesson, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::Lesson, id_mysql >::object_type >
  access::object_traits_impl< ::Lesson, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Lesson, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
