/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `pushClients`;

CREATE TABLE `pushClients` (
  `deviceId` VARCHAR(255) NOT NULL PRIMARY KEY,
  `registrationId` VARCHAR(255) NOT NULL,
  `className` VARCHAR(128) NULL)
 ENGINE=InnoDB;

